const itemList = [
  {
    img: "https://neal.fun/spend/images/big-mac.jpg",
    title: "Big Mac",
    money: 2,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/flip-flops.jpg",
    title: "Flip Flops",
    money: 3,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/coca-cola-pack.jpg",
    title: "Coca-Cola Pack",
    money: 5,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/movie-ticket.jpg",
    title: "Movie Ticket",
    money: 12,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/book.jpg",
    title: "Book",
    money: 15,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/lobster-dinner.jpg",
    title: "Lobster Dinner",
    money: 45,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/video-game.jpg",
    title: "Video Game",
    money: 60,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/amazon-echo.jpg",
    title: "Amazon Echo",
    money: 99,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/year-of-netflix.jpg",
    title: "Year of Netflix",
    money: 100,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/air-jordans.jpg",
    title: "Air Jordans",
    money: 125,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/airpods.jpg",
    title: "Airpods",
    money: 199,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/gaming-console.jpg",
    title: "Gaming Console",
    money: 299,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/drone.jpg",
    title: "Drone",
    money: 350,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/smartphone.jpg",
    title: "Smartphone",
    money: 699,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/bike.jpg",
    title: "Bike",
    money: 800,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/kitten.jpg",
    title: "Kitten",
    money: 1500,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/puppy.jpg",
    title: "Puppy",
    money: 1500,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/auto-rickshaw.jpg",
    title: "Auto Rickshaw",
    money: 2300,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/horse.jpg",
    title: "Horse",
    money: 2500,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/acre-of-farmland.jpg",
    title: "Acre of Farmland",
    money: 3000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/designer-handbag.jpg",
    title: "Designer Handbag",
    money: 5500,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/hot-tub.jpg",
    title: "Hot Tub",
    money: 6000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/luxury-wine.jpg",
    title: "Luxury Wine",
    money: 7000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/diamond-ring.jpg",
    title: "Diamond Ring",
    money: 10000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/jet-ski.jpg",
    title: "Jet Ski",
    money: 12000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/rolex.jpg",
    title: "Rolex",
    money: 15000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/ford-f-150.jpg",
    title: "Ford F-150",
    money: 30000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/tesla.jpg",
    title: "Tesla",
    money: 75000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/monster-truck.jpg",
    title: "Monster Truck",
    money: 150000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/ferrari.jpg",
    title: "Ferrari",
    money: 250000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/single-family-home.jpg",
    title: "Single Family Home",
    money: 300000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/gold-bar.jpg",
    title: "Gold Bar",
    money: 700000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/mcdonalds-franchise.jpg",
    title: "McDonalds Franchise",
    money: 1500000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/superbowl-ad.jpg",
    title: "Superbowl Ad",
    money: 5250000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/yacht.jpg",
    title: "Yatch",
    money: 7500000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/m1-abrams.jpg",
    title: "M1 Abrams",
    money: 8000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/formula-1-car.jpg",
    title: "Formula 1 Car",
    money: 15000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/apache-helicopter.jpg",
    title: "Apache Helicopter",
    money: 31000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/mansion.jpg",
    title: "Mansion",
    money: 45000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/make-a-movie.jpg",
    title: "Make a Movie",
    money: 100000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/boeing-747.jpg",
    title: "Boeing 747",
    money: 148000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/mona-lisa.jpg",
    title: "Mona Lisa",
    money: 780000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/skyscraper.jpg",
    title: "Skyscraper",
    money: 850000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/cruise-ship.jpg",
    title: "Cruise Ship",
    money: 930000000,
    amount: 0,
  },
  {
    img: "https://neal.fun/spend/images/nba-team.jpg",
    title: "Nba Team",
    money: 2120000000,
    amount: 0,
  },
];
export default itemList;
